version: "3.7"
services:
    flask-app:
        build: ./back
        ports: 
            - "5000:5000"
        networks:
            - default
    react-nginx-app:
        build: ./front
        ports: 
            - "80:80"
        networks:
            - default
volumes:
    persistent:
